[project]
name = "watlow-f4"
version = "0.2.2"
description = "Python driver for the Watlow F4 temperature controller via Modbus RTU"
license = "MIT"
readme = "README.md"
authors = [
    { name = "Alec Vercruysse", email = "alec@verc.net" }
]
requires-python = ">=3.8"
dependencies = [
    "minimalmodbus>=2.1.1",
]

[project.urls]
source = "https://github.com/anwar-lab-ucb/watlow_f4"

[build-system]
requires = ["uv_build>=0.10.11,<0.11.0"]
build-backend = "uv_build"


[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
